#!/bin/bash
echo -e ""
echo -e "» menu          : Menampilkan daftar perintah"
echo -e "» user-add      : Membuat akun SSH & OpenVPN"
echo -e "» trial         : Membuat akun trial"
echo -e "» user-del      : Menghapus akun SSH & OpenVPN"
echo -e "» user-login    : Cek user login"
echo -e "» user-list     : Daftar member SSH & OpenVPN"
echo -e "» expdel        : Delete user expired"
echo -e "» resvis        : Restart service dropbear, webmin"
echo -e "                 squid3, OpenVPN,Stunnel dan SSH"
echo -e "» reboot        : Reboot VPS"
echo -e "» speedtest     : Speedtest VPS"
echo -e "» info          : Menampilkan informasi sistem"
echo -e "» about         : Info script auto install"
echo -e "» exit          : Keluar dari terminal SSH"
echo -e "~sivoi~"
